## Global configuration for the automation framework
##
## NOTE: This file is deprecated. The primary configuration is now in
## the root settings.yaml file. This file is kept for backward compatibility
## but should not be modified. All new configuration should be added to
## the root settings.yaml file.

database:
  # Location of the SQLite database used to store versioned test sets and results.
  url: sqlite:///./test_sets.db

allure:
  # Directory where Allure result files are written.
  results_dir: reports

router:
  # Default classification thresholds.  Natural‑language classification can be
  # tuned by adjusting these values.
  ui_keywords: ["click", "navigate", "button", "page", "browser"]
  api_keywords: ["GET", "POST", "PUT", "DELETE", "endpoint", "url"]
  mobile_keywords: ["tap", "swipe", "mobile", "android", "ios"]
  sql_keywords: ["insert", "update", "delete", "select", "verify"]

mcp:
  # Retry settings for all MCPs
  max_retries: 3
  retry_interval_seconds: 2

ui:
  browser: chromium
  headless: true
  # self‑healing settings
  self_heal: true

api:
  # Base URL for API MCP.  In the self‑test this points to httpbin.org which
  # provides simple echo endpoints.
  base_url: https://httpbin.org

mobile:
  server_url: http://localhost:4723/wd/hub
  platform_name: Android
  device_name: emulator-5554
  app_path: ./apps/sample.apk

dashboard:
  host: 0.0.0.0
  port: 8000

versioning:
  # Similarity threshold used when comparing test set versions.  Values above
  # this threshold will trigger a duplicate warning but still save the new version.
  similarity_threshold: 0.8
  # Method used to compute similarity between test set versions.  Allowed
  # values are 'sequence' (difflib.SequenceMatcher) or 'embedding'.  The
  # embedding method uses TF‑IDF and cosine distance for a more
  # semantic comparison.
  method: "embedding"

# OpenAI and LLM settings.  If an API key is provided the framework will
# use ChatGPT to classify steps and translate natural language into API
# requests and SQL.  If `use_local` is true or the API key is missing
# then rule‑based fallbacks are used instead.
openai:
  api_key: null
  model: "gpt-3.5-turbo"
  use_local: true

# Locator repository settings.  The repository stores per‑step
# selectors and locators in a SQLite database.  The default path
# locators.db will be created in the working directory.  Use a
# full path or a ``sqlite:///`` URI to customise the location.
locator_repo:
  path: sqlite:///./locators.db

# Wait repository settings.  The wait repo contains lists of
# spinners and overlay selectors (for UI and mobile) that are used
# by wait_utils to wait for pages to stabilise.  Spinners learned
# during execution will be appended to this file.
wait_repo:
  path: ./wait_repo.yaml

# Concurrency settings.  When enabled the MCP router will dispatch test
# cases to a thread pool so that UI, API, mobile and SQL tests run in
# parallel.  Increase the `workers` count to fully utilise multi‑core
# machines.
concurrency:
  enabled: false
  workers: 4

# Security / RBAC settings.  The dashboard uses JWTs to authenticate
# users.  Provide a long, random `secret_key` and configure users
# with hashed passwords.  Roles can be "admin" or "viewer".  See
# automation_framework/security/auth.py for details.
security:
  secret_key: "changeme"
  algorithm: "HS256"
  access_token_expire_minutes: 60
  users:
    - username: "admin"
      # In environments where passlib is unavailable hashed passwords cannot be
      # verified.  For demonstration and self‑testing purposes the plain
      # password can be stored here.  In production replace with a bcrypt
      # hash and ensure ``passlib[bcrypt]`` is installed.
      password_hash: "admin"
      role: "admin"
    - username: "user"
      password_hash: "user"
      role: "viewer"

# Alerting settings.  Configure Slack and SMTP credentials to receive
# notifications when test runs encounter unrecoverable errors.  Leave
# values empty to disable.
alerts:
  slack_webhook_url: null
  email:
    smtp_server: null
    smtp_port: 587
    sender: null
    recipient: null
    username: null
    password: null